# Generated by Django 5.2.14 on 2026-05-28 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=150, unique=True)),
                ('rule_type', models.CharField(choices=[('PAIRWISE_AND', 'Pairwise And'), ('ADVANCED_EXPRESSION', 'Advanced Expression')], default='PAIRWISE_AND', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('flag', models.CharField(max_length=255)),
                ('insight', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('domain_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules_as_domain_a', to='assessments.domain')),
                ('domain_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules_as_domain_b', to='assessments.domain')),
            ],
        ),
    ]
