# Generated by Django 5.2.14 on 2026-06-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_survey_simulation',
            field=models.BooleanField(default=False, help_text='Show the simulate survey completion button on the dashboard (for testing).'),
        ),
    ]
